name: Vercel Auto Setup and Deploy

on:
  push:
    branches: [main, master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm i -g vercel

      - name: Check if project already exists on Vercel
        id: check-project
        run: |
          PROJECT_EXISTS=$(vercel --token ${{ secrets.VERCEL_TOKEN }} ls --json | grep -q "${{ github.event.repository.name }}" && echo "true" || echo "false")
          echo "project_exists=$PROJECT_EXISTS" >> $GITHUB_OUTPUT

      - name: First-time setup - Link and deploy project
        if: steps.check-project.outputs.project_exists == 'false'
        run: |
          vercel --token ${{ secrets.VERCEL_TOKEN }} link --yes
          vercel --token ${{ secrets.VERCEL_TOKEN }} deploy --prod --yes
          echo "Initial project setup complete on Vercel."

      - name: Regular deployment - Let Vercel handle it
        if: steps.check-project.outputs.project_exists == 'true'
        run: |
          echo "Project already exists on Vercel."
          echo "Vercel's GitHub integration will handle this deployment automatically."
